apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rtl.name" . }}
  labels:
    app: {{ template "rtl.name" . }}
    chart: {{ template "rtl.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Release.IsInstall }}
  multipass: {{ randAlphaNum 24 | b64enc }}
  {{ else }}
  # `index` function is necessary because the property name contains a dash.
  # Otherwise (...).data.db_password would have worked too.
  multipass: {{ index (lookup "v1" "Secret" .Release.Namespace "rtl").data "multipass" }}
  {{ end }}
  admin.macaroon: |
    {{ index (lookup "v1" "Secret" .Values.configuration.lndNamespace "macaroons").data "admin.macaroon" }}
  loop.macaroon: |
    {{ index (lookup "v1" "Secret" .Values.configuration.lndNamespace "macaroons").data "loop.macaroon" }}
  pool.macaroon: |
    {{ index (lookup "v1" "Secret" .Values.configuration.lndNamespace "macaroons").data "pool.macaroon" }}

