apiVersion: v1
kind: Service
metadata:
  name: {{ template "rtl.fullname" . }}
  labels:
    app: {{ template "rtl.name" . }}
    chart: {{ template "rtl.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.configuration.externalIp }}
spec:
  type: LoadBalancer
  ports:
    - name: rtl-port
      port: 8080
      targetPort: rtl-port
  selector:
    app: {{ template "rtl.name" . }}
    release: {{ .Release.Name }}
